spring:
  cloud:
    gcp:
      pubsub:
        enabled: false
        project-id: test-project-id
        credentials:
          location: file:C:/Users/chris/.gcp/service-account-key-v2.json
        topic: credit-transactions
  server:
    port: 8080